// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from service.proto</summary>
public static partial class ServiceReflection {

  #region Descriptor
  /// <summary>File descriptor for service.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ServiceReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1zZXJ2aWNlLnByb3RvIiAKDEhlbGxvUmVxdWVzdBIQCghncmVldGluZxgB",
          "IAEoCSIeCg1IZWxsb1Jlc3BvbnNlEg0KBXJlcGx5GAEgASgJMjkKDEhlbGxv",
          "U2VydmljZRIpCghTYXlIZWxsbxINLkhlbGxvUmVxdWVzdBoOLkhlbGxvUmVz",
          "cG9uc2ViBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::HelloRequest), global::HelloRequest.Parser, new[]{ "Greeting" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::HelloResponse), global::HelloResponse.Parser, new[]{ "Reply" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class HelloRequest : pb::IMessage<HelloRequest> {
  private static readonly pb::MessageParser<HelloRequest> _parser = new pb::MessageParser<HelloRequest>(() => new HelloRequest());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<HelloRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ServiceReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HelloRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HelloRequest(HelloRequest other) : this() {
    greeting_ = other.greeting_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HelloRequest Clone() {
    return new HelloRequest(this);
  }

  /// <summary>Field number for the "greeting" field.</summary>
  public const int GreetingFieldNumber = 1;
  private string greeting_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Greeting {
    get { return greeting_; }
    set {
      greeting_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as HelloRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(HelloRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Greeting != other.Greeting) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Greeting.Length != 0) hash ^= Greeting.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Greeting.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Greeting);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Greeting.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Greeting);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(HelloRequest other) {
    if (other == null) {
      return;
    }
    if (other.Greeting.Length != 0) {
      Greeting = other.Greeting;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          Greeting = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class HelloResponse : pb::IMessage<HelloResponse> {
  private static readonly pb::MessageParser<HelloResponse> _parser = new pb::MessageParser<HelloResponse>(() => new HelloResponse());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<HelloResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ServiceReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HelloResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HelloResponse(HelloResponse other) : this() {
    reply_ = other.reply_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HelloResponse Clone() {
    return new HelloResponse(this);
  }

  /// <summary>Field number for the "reply" field.</summary>
  public const int ReplyFieldNumber = 1;
  private string reply_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Reply {
    get { return reply_; }
    set {
      reply_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as HelloResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(HelloResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Reply != other.Reply) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Reply.Length != 0) hash ^= Reply.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Reply.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Reply);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Reply.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Reply);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(HelloResponse other) {
    if (other == null) {
      return;
    }
    if (other.Reply.Length != 0) {
      Reply = other.Reply;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          Reply = input.ReadString();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
